CREATE OR REPLACE FUNCTION FUN_EMAIL_ADMINISTRADOR_RESERV RETURN VARCHAR2 IS
  RESULTADO VARCHAR2(4000);
  ---FUN_EMAIL_ADMINISTRADOR_RESERVA
BEGIN
  
  RESULTADO:= 'ederaparecidoleite2013@gmail.com; evolutiondelphixe@gmail.com';

  RETURN(RESULTADO);
END FUN_EMAIL_ADMINISTRADOR_RESERV;
/
