ALTER TABLE ASSRESER ADD(NCODIUSUAR           NUMBER(7) NULL);

COMMENT ON COLUMN ASSRESER.NCODIUSUAR IS 'Codigo do usuario';

CREATE  INDEX FK_ASSRESER_SEGUSUAR ON ASSRESER
(NCODIUSUAR   ASC);

ALTER TABLE ASSRESER
ADD CONSTRAINT ASSRESER_SEGUSUAR FOREIGN KEY (NCODIUSUAR) REFERENCES SEGUSUAR (NCODIUSUAR);

ALTER TABLE SEGUSUAR
  ADD (CPVNRUSUAR VARCHAR2(1));

COMMENT ON COLUMN SEGUSUAR.CPVNRUSUAR IS 'Permiti visualizar funcionario na lista de reserva';



DROP TABLE ASSAVAFI CASCADE CONSTRAINTS PURGE;



CREATE TABLE ASSAVAFI
(
	NCODIAVAFI           NUMBER(7) NOT NULL ,
	DDATAAVAFI           DATE NULL ,
	CPUTSAVAFI           VARCHAR2(1000) NULL ,
	CEXCOAVAFI           VARCHAR2(1000) NULL ,
	CQUEXAVAFI           VARCHAR2(1000) NULL ,
	CPULSAVAFI           VARCHAR2(1000) NULL ,
	CAVPAAVAFI           VARCHAR2(1000) NULL ,
	CAUPUAVAFI           VARCHAR2(1000) NULL ,
	CAUCAAVAFI           VARCHAR2(1000) NULL ,
	CMAOSAVAFI           VARCHAR2(1000) NULL ,
	CAPESAVAFI           VARCHAR2(1000) NULL ,
	CAXILAVAFI           VARCHAR2(1000) NULL ,
	CREINAVAFI           VARCHAR2(1000) NULL ,
	CMANCAVAFI           VARCHAR2(1000) NULL ,
	CCOCAAVAFI           VARCHAR2(1000) NULL ,
	COUVIAVAFI           VARCHAR2(1000) NULL ,
	CNARIAVAFI           VARCHAR2(1000) NULL ,
	CGARGAVAFI           VARCHAR2(1000) NULL ,
	CDENTAVAFI           VARCHAR2(1000) NULL ,
	CAPGUAVAFI           VARCHAR2(1000) NULL ,
	CANMFAVAFI           VARCHAR2(1000) NULL ,
	COBSEAVAFI           VARCHAR2(2000) NULL ,
	NCODIFUNCI           NUMBER(7) NOT NULL 
);




COMMENT ON COLUMN ASSAVAFI.NCODIAVAFI IS 'Codigo da avaliacao fisica';




COMMENT ON COLUMN ASSAVAFI.DDATAAVAFI IS 'Data da avaliacao fisica';




COMMENT ON COLUMN ASSAVAFI.CPUTSAVAFI IS 'O examinado pode utilizar a sauna';




COMMENT ON COLUMN ASSAVAFI.CEXCOAVAFI IS 'Ha necessidade de exames complementares';




COMMENT ON COLUMN ASSAVAFI.CQUEXAVAFI IS 'Quais exames complementares';




COMMENT ON COLUMN ASSAVAFI.CPULSAVAFI IS 'Pulso';




COMMENT ON COLUMN ASSAVAFI.CAVPAAVAFI IS 'PA';




COMMENT ON COLUMN ASSAVAFI.CAUPUAVAFI IS 'Ausculta pulmonar';




COMMENT ON COLUMN ASSAVAFI.CAUCAAVAFI IS 'Ausculta cardiaca';




COMMENT ON COLUMN ASSAVAFI.CMAOSAVAFI IS 'Maos';




COMMENT ON COLUMN ASSAVAFI.CAPESAVAFI IS 'Pes';




COMMENT ON COLUMN ASSAVAFI.CAXILAVAFI IS 'Axilas';




COMMENT ON COLUMN ASSAVAFI.CREINAVAFI IS 'Regiao Inguinal';




COMMENT ON COLUMN ASSAVAFI.CMANCAVAFI IS 'Manchas';




COMMENT ON COLUMN ASSAVAFI.CCOCAAVAFI IS 'Couro cabeludo';




COMMENT ON COLUMN ASSAVAFI.COUVIAVAFI IS 'Ouvidos';




COMMENT ON COLUMN ASSAVAFI.CNARIAVAFI IS 'Nariz';




COMMENT ON COLUMN ASSAVAFI.CGARGAVAFI IS 'Garganta';




COMMENT ON COLUMN ASSAVAFI.CDENTAVAFI IS 'Dentes';




COMMENT ON COLUMN ASSAVAFI.CAPGUAVAFI IS 'Apareclho genital urinario';




COMMENT ON COLUMN ASSAVAFI.CANMFAVAFI IS 'Antecedentes morbidos familiares e pessoas de interesse';




COMMENT ON COLUMN ASSAVAFI.COBSEAVAFI IS 'Observacoes';




COMMENT ON COLUMN ASSAVAFI.NCODIFUNCI IS 'Codigo do cadastro de funcionarios';



CREATE UNIQUE INDEX PK_NCODIAVAFI ON ASSAVAFI
(NCODIAVAFI   ASC);



ALTER TABLE ASSAVAFI
	ADD CONSTRAINT  PK_NCODIAVAFI PRIMARY KEY (NCODIAVAFI);



CREATE  INDEX FK_ASSAVAFI_ASSFUNCI ON ASSAVAFI
(NCODIFUNCI   ASC);



ALTER TABLE ASSAVAFI
	ADD (CONSTRAINT ASSAVAFI_ASSFUNCI FOREIGN KEY (NCODIFUNCI) REFERENCES ASSFUNCI (NCODIFUNCI));





CREATE SEQUENCE ASS_SASSAVAFI
MINVALUE 1
MAXVALUE 9999999999999999999999999999
START WITH 1
INCREMENT BY 1
CACHE 20;
