
DROP TABLE ASSRESER CASCADE CONSTRAINTS PURGE;



DROP TABLE ASSFUNCI CASCADE CONSTRAINTS PURGE;



DROP TABLE ASSCHURR CASCADE CONSTRAINTS PURGE;



CREATE TABLE ASSCHURR
(
  NCODICHURR           NUMBER(7) NOT NULL ,
  CDESCCHURR           VARCHAR2(60) NULL 
);




COMMENT ON COLUMN ASSCHURR.NCODICHURR IS 'Codigo do cadastro de churrasqueiras';




COMMENT ON COLUMN ASSCHURR.CDESCCHURR IS 'Descricao do cadastro de churrasqueiras';



CREATE UNIQUE INDEX PK_NCODICHURR ON ASSCHURR
(NCODICHURR   ASC);



ALTER TABLE ASSCHURR
  ADD CONSTRAINT  PK_NCODICHURR PRIMARY KEY (NCODICHURR);



CREATE TABLE ASSFUNCI
(
  NCODIFUNCI           NUMBER(7) NOT NULL ,
  NEMPRFUNCI           NUMBER(1) NULL ,
  NPESSFUNCI           NUMBER(7) NULL ,
  CCRACFUNCI           VARCHAR2(10) NULL ,
  CNOMEFUNCI           VARCHAR2(100) NULL ,
  CSITUFUNCI           VARCHAR2(1) NULL 
);




COMMENT ON COLUMN ASSFUNCI.NCODIFUNCI IS 'Codigo do cadastro de funcionarios';




COMMENT ON COLUMN ASSFUNCI.NEMPRFUNCI IS 'Empresa do funcionario';




COMMENT ON COLUMN ASSFUNCI.NPESSFUNCI IS 'Pessoa do funcionario';




COMMENT ON COLUMN ASSFUNCI.CCRACFUNCI IS 'Cracha do funcionario';




COMMENT ON COLUMN ASSFUNCI.CNOMEFUNCI IS 'Nome do funcionario';




COMMENT ON COLUMN ASSFUNCI.CSITUFUNCI IS 'Situacao do funcionario';



CREATE UNIQUE INDEX PK_NCODIFUNCI ON ASSFUNCI
(NCODIFUNCI   ASC);



ALTER TABLE ASSFUNCI
  ADD CONSTRAINT  PK_NCODIFUNCI PRIMARY KEY (NCODIFUNCI);



CREATE TABLE ASSRESER
(
  NCODIRESER           NUMBER(7) NOT NULL ,
  DINICRESER           DATE NULL ,
  DFINARESER           DATE NULL ,
  CSTATRESER           VARCHAR2(20) NULL ,
  COBSERESER           VARCHAR2(1000) NULL ,
  NCODICHURR           NUMBER(7) NOT NULL ,
  NCODIFUNCI           NUMBER(7) NOT NULL 
);




COMMENT ON COLUMN ASSRESER.NCODICHURR IS 'Codigo do cadastro de churrasqueiras';




COMMENT ON COLUMN ASSRESER.NCODIFUNCI IS 'Codigo do cadastro de funcionarios';



CREATE UNIQUE INDEX PK_NCODIRESER ON ASSRESER
(NCODIRESER   ASC);



ALTER TABLE ASSRESER
  ADD CONSTRAINT  PK_NCODIRESER PRIMARY KEY (NCODIRESER);



CREATE  INDEX FK_ASSRESER_ASSCHURR ON ASSRESER
(NCODICHURR   ASC);



CREATE  INDEX FK_ASSRESER_ASSFUNCI ON ASSRESER
(NCODIFUNCI   ASC);



ALTER TABLE ASSRESER
  ADD (CONSTRAINT ASSRESER_ASSCHURR FOREIGN KEY (NCODICHURR) REFERENCES ASSCHURR (NCODICHURR));



ALTER TABLE ASSRESER
  ADD (CONSTRAINT ASSRESER_ASSFUNCI FOREIGN KEY (NCODIFUNCI) REFERENCES ASSFUNCI (NCODIFUNCI));
  
ALTER TABLE SEGUSUAR
	ADD (CPMRCUSUAR VARCHAR2(1));



COMMENT ON COLUMN SEGUSUAR.CPMRCUSUAR IS 'Permiti manipular reserva de churrasqueira';  

-- Create sequence 
create sequence ASS_SASSCHURR
minvalue 1
maxvalue 9999999999999999999999999999
start with 3
increment by 1
cache 20;

-- Create sequence 
create sequence ASS_SASSRESER
minvalue 1
maxvalue 9999999999999999999999999999
start with 3
increment by 1
cache 20;

-- Create sequence 
create sequence ASS_SASSFUNCI
minvalue 1
maxvalue 9999999999999999999999999999
start with 3
increment by 1
cache 20;



