
ALTER TABLE ASSRESER
  ADD (CTECORESER VARCHAR2(16));



COMMENT ON COLUMN ASSRESER.CTECORESER IS 'Telefone de contato';

CREATE TABLE ASSPECHU
(
  NCODIPECHU           NUMBER(7) NOT NULL ,
  NQTDEPECHU           NUMBER(4) NULL ,
  CDESCPECHU           VARCHAR2(60) NULL ,
  NCODICHURR           NUMBER(7) NOT NULL 
);




COMMENT ON COLUMN ASSPECHU.NCODIPECHU IS 'Codigo do cadastro de pertence';




COMMENT ON COLUMN ASSPECHU.NQTDEPECHU IS 'Quantidade de pertence';




COMMENT ON COLUMN ASSPECHU.CDESCPECHU IS 'Descricao do pertence';




COMMENT ON COLUMN ASSPECHU.NCODICHURR IS 'Codigo do cadastro de churrasqueiras';



CREATE UNIQUE INDEX PK_NCODIPECHU ON ASSPECHU
(NCODIPECHU   ASC);



CREATE  INDEX FK_ASSPECHU_ASSCHURR ON ASSPECHU
(NCODICHURR   ASC);



ALTER TABLE ASSPECHU
ADD CONSTRAINT  PK_NCODIPECHU PRIMARY KEY (NCODIPECHU);



ALTER TABLE ASSPECHU
ADD CONSTRAINT ASSPECHU_ASSCHURR FOREIGN KEY (NCODICHURR) REFERENCES ASSCHURR (NCODICHURR);

-- CREATE SEQUENCE 
CREATE SEQUENCE ASS_SASSPECHU
MINVALUE 1
MAXVALUE 9999999999999999999999999999
START WITH 1
INCREMENT BY 1
CACHE 20;
