DROP TABLE SEGUSUAR CASCADE CONSTRAINTS PURGE;

CREATE TABLE SEGUSUAR
(
  NCODIUSUAR           NUMBER(7) NOT NULL ,
  CNOMEUSUAR           VARCHAR2(60) NULL ,
  CPASSUSUAR           VARCHAR2(12) NULL ,
  CEMAIUSUAR           VARCHAR2(60) NULL ,
  CADMIUSUAR           VARCHAR2(1) DEFAULT  'N'  NULL ,
  CSTATUSUAR           VARCHAR2(1) DEFAULT  'A'  NULL ,
  CLOGIUSUAR           VARCHAR2(20) NULL 
);

COMMENT ON COLUMN SEGUSUAR.NCODIUSUAR IS 'Codigo do usuario';
COMMENT ON COLUMN SEGUSUAR.CNOMEUSUAR IS 'Nome do usuario';
COMMENT ON COLUMN SEGUSUAR.CPASSUSUAR IS 'Password do usuario';
COMMENT ON COLUMN SEGUSUAR.CEMAIUSUAR IS 'E-mail do usuario';
COMMENT ON COLUMN SEGUSUAR.CADMIUSUAR IS 'O usuario e um administrador do sistema (sim ou nao)';
COMMENT ON COLUMN SEGUSUAR.CSTATUSUAR IS 'Status do usuario (ativo ou inativo)';
COMMENT ON COLUMN SEGUSUAR.CLOGIUSUAR IS 'Login do usuario do sistema';

CREATE UNIQUE INDEX PK_SEGUSUAR ON SEGUSUAR
(NCODIUSUAR   ASC);

ALTER TABLE SEGUSUAR
  ADD CONSTRAINT  PK_SEGUSUAR PRIMARY KEY (NCODIUSUAR);

--

DROP TABLE SEGSISTE CASCADE CONSTRAINTS PURGE;

CREATE TABLE SEGSISTE
(
	NCODISISTE           NUMBER(7) NOT NULL ,
	CDESCSISTE           VARCHAR2(60) NULL ,
	CSTATSISTE           VARCHAR2(1) NULL 
);

COMMENT ON COLUMN SEGSISTE.NCODISISTE IS 'Codigo do cadastro de sistemas';
COMMENT ON COLUMN SEGSISTE.CDESCSISTE IS 'Descricao do cadastro de sistemas';
COMMENT ON COLUMN SEGSISTE.CSTATSISTE IS 'Status do cadastro de sistemas';

CREATE UNIQUE INDEX PK_SEGSISTE ON SEGSISTE
(NCODISISTE   ASC);

ALTER TABLE SEGSISTE
	ADD CONSTRAINT  PK_SEGSISTE PRIMARY KEY (NCODISISTE);

--

DROP TABLE FINCONFI CASCADE CONSTRAINTS PURGE;

CREATE TABLE FINCONFI
(
	NCODICONFI           NUMBER(6) NOT NULL ,
	CDESCCONFI           VARCHAR2(40) NULL ,
	NSAATCONFI           NUMBER(14,2) NULL 
);

COMMENT ON COLUMN FINCONFI.NCODICONFI IS 'Codigo da conta financeira';
COMMENT ON COLUMN FINCONFI.CDESCCONFI IS 'Descricao da conta financeira';
COMMENT ON COLUMN FINCONFI.NSAATCONFI IS 'Saldo atualizado da conta financeira';

CREATE UNIQUE INDEX PK_FINCONFI ON FINCONFI
(NCODICONFI   ASC);

ALTER TABLE FINCONFI
	ADD CONSTRAINT  PK_FINCONFI PRIMARY KEY (NCODICONFI);
  
--

DROP TABLE FINGREDE CASCADE CONSTRAINTS PURGE;

CREATE TABLE FINGREDE
(
	NCODIGREDE           NUMBER(6) NOT NULL ,
	CDESCGREDE           VARCHAR2(40) NULL ,
	CTIPOGREDE           VARCHAR2(1) NULL 
);

COMMENT ON COLUMN FINGREDE.NCODIGREDE IS 'Codigo do grupo de receita / despesa';
COMMENT ON COLUMN FINGREDE.CDESCGREDE IS 'Descricao do grupo de receita / despesa';
COMMENT ON COLUMN FINGREDE.CTIPOGREDE IS 'Tipo do grupo de receita / despesa';

CREATE UNIQUE INDEX PK_FINGREDE ON FINGREDE
(NCODIGREDE   ASC);

ALTER TABLE FINGREDE
	ADD CONSTRAINT  PK_FINGREDE PRIMARY KEY (NCODIGREDE);

--

DROP TABLE FINSREDE CASCADE CONSTRAINTS PURGE;

CREATE TABLE FINSREDE
(
	NCODISREDE           NUMBER(6) NOT NULL ,
	CDESCSREDE           VARCHAR2(40) NULL ,
	NCODIGREDE           NUMBER(6) NOT NULL 
);

COMMENT ON COLUMN FINSREDE.NCODISREDE IS 'Codigo do subgrupo de receita / despesa';
COMMENT ON COLUMN FINSREDE.CDESCSREDE IS 'Descricao do subgrupo de receita / despesa';
COMMENT ON COLUMN FINSREDE.NCODIGREDE IS 'Codigo do grupo de receita / despesa';

CREATE UNIQUE INDEX PK_FINSREDE ON FINSREDE
(NCODISREDE   ASC);

ALTER TABLE FINSREDE
	ADD CONSTRAINT  PK_FINSREDE PRIMARY KEY (NCODISREDE);

CREATE  INDEX FK_FINGREDE ON FINSREDE
(NCODIGREDE   ASC);

ALTER TABLE FINSREDE
	ADD (CONSTRAINT FINSREDE_FINGREDE FOREIGN KEY (NCODIGREDE) REFERENCES FINGREDE (NCODIGREDE));
  
--

DROP TABLE FINFINAN CASCADE CONSTRAINTS PURGE;

CREATE TABLE FINFINAN
(
	NCODIFINAN           NUMBER(10) NOT NULL ,
	DDATAFINAN           DATE NULL ,
	CTIPOFINAN           VARCHAR2(1) NULL ,
	CDESCFINAN           VARCHAR2(100) NULL ,
	NVALOFINAN           NUMBER(14,2) NULL ,
	NCODIGREDE           NUMBER(6) NULL ,
	NCODISREDE           NUMBER(6) NULL ,
	NORIGCONFI           NUMBER(6) NULL ,
	NDESTCONFI           NUMBER(6) NULL 
);

COMMENT ON COLUMN FINFINAN.NCODIFINAN IS 'Codigo do movimento financeiro';
COMMENT ON COLUMN FINFINAN.DDATAFINAN IS 'Data do movimento financeiro';
COMMENT ON COLUMN FINFINAN.CTIPOFINAN IS 'Tipo do movimento financeiro';
COMMENT ON COLUMN FINFINAN.CDESCFINAN IS 'Descricao do movimento financeiro';
COMMENT ON COLUMN FINFINAN.NVALOFINAN IS 'Valor do movimento financeiro';
COMMENT ON COLUMN FINFINAN.NCODIGREDE IS 'Codigo do grupo de receita / despesa';
COMMENT ON COLUMN FINFINAN.NCODISREDE IS 'Codigo do subgrupo de receita / despesa';
COMMENT ON COLUMN FINFINAN.NORIGCONFI IS 'Codigo da conta financeira';
COMMENT ON COLUMN FINFINAN.NDESTCONFI IS 'Codigo da conta financeira';

CREATE UNIQUE INDEX PK_FINFINAN ON FINFINAN
(NCODIFINAN   ASC);

ALTER TABLE FINFINAN
	ADD CONSTRAINT  PK_FINFINAN PRIMARY KEY (NCODIFINAN);

CREATE  INDEX FK_FINGREDE1 ON FINFINAN
(NCODIGREDE   ASC);

CREATE  INDEX FK_FINSREDE ON FINFINAN
(NCODISREDE   ASC);

CREATE  INDEX FK_FINCONFI_ORIGEM ON FINFINAN
(NORIGCONFI   ASC);

CREATE  INDEX FK_FINCONFI_DESTINO ON FINFINAN
(NDESTCONFI   ASC);

ALTER TABLE FINFINAN
	ADD (CONSTRAINT FINFINAN_FINGREDE FOREIGN KEY (NCODIGREDE) REFERENCES FINGREDE (NCODIGREDE) ON DELETE SET NULL);

ALTER TABLE FINFINAN
	ADD (CONSTRAINT FINFINAN_FINSREDE FOREIGN KEY (NCODISREDE) REFERENCES FINSREDE (NCODISREDE) ON DELETE SET NULL);

ALTER TABLE FINFINAN
	ADD (CONSTRAINT FINFINAN_FINCONFI_ORIGEM FOREIGN KEY (NORIGCONFI) REFERENCES FINCONFI (NCODICONFI) ON DELETE SET NULL);

ALTER TABLE FINFINAN
	ADD (CONSTRAINT FINFINAN_FINCONFI_DESTINO FOREIGN KEY (NDESTCONFI) REFERENCES FINCONFI (NCODICONFI) ON DELETE SET NULL);


  






